# Generated by Django 4.2.4 on 2024-05-02 04:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('text', models.TextField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teamplates',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('semester', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('year_number', models.IntegerField(help_text='ใส่ตัวเลขปี 4 ตัว', validators=[django.core.validators.MinValueValidator(2567), django.core.validators.MaxValueValidator(2570)], verbose_name='ปี')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsite.teamplates')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='formsite.templatedata')),
            ],
        ),
        migrations.CreateModel(
            name='LineTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_token', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('class_code', models.CharField(max_length=10)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('is_teacher_form', models.BooleanField(default=False)),
                ('semester', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('section', models.CharField(max_length=2)),
                ('year_number', models.IntegerField(help_text='ใส่ตัวเลขปี 4 ตัว', validators=[django.core.validators.MinValueValidator(1999), django.core.validators.MaxValueValidator(3100)], verbose_name='ปี')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('expired', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsite.form')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('response', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('response_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('assessment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsite.assessmentitem')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsite.form'),
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='formsite.assessmentitem'),
        ),
    ]
