# Generated by Django 4.2.4 on 2024-04-24 13:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clo',
            fields=[
                ('text', models.TextField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('class_code', models.CharField(max_length=10)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('school_year', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('section', models.CharField(max_length=2)),
                ('year_number', models.IntegerField(help_text='ใส่ตัวเลขปี 4 ตัว', validators=[django.core.validators.MinValueValidator(1999), django.core.validators.MaxValueValidator(3100)], verbose_name='ปี')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Form_plos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('school_year', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('year_number', models.IntegerField(help_text='ใส่ตัวเลขปี 4 ตัว', validators=[django.core.validators.MinValueValidator(2567), django.core.validators.MaxValueValidator(2570)], verbose_name='ปี')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('students_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='PLOs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsite.form_plos')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='formsite.plos')),
            ],
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('response_clo', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('clo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsite.clo')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsite.form')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clo',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsite.form'),
        ),
        migrations.AddField(
            model_name='clo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='formsite.clo'),
        ),
        migrations.CreateModel(
            name='AuthorizedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_list', models.CharField(max_length=10)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsite.form')),
            ],
        ),
    ]
