# Generated by Django 4.2.4 on 2024-02-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='clo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='plo',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='section',
        ),
        migrations.RemoveField(
            model_name='userevaluation',
            name='answers',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='clo',
        ),
        migrations.DeleteModel(
            name='plo',
        ),
        migrations.DeleteModel(
            name='UserEvaluation',
        ),
    ]
