# Generated by Django 4.2.4 on 2024-05-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0002_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], max_length=100),
        ),
    ]
