# Generated by Django 4.2.4 on 2024-02-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0002_students_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='stu_list',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
