# Generated by Django 4.2.4 on 2024-02-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0002_answer_userevaluation_clo_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
