# Generated by Django 4.2.4 on 2024-05-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0003_alter_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
