# Generated by Django 4.2.4 on 2024-05-04 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formsite', '0003_assessmentitem_template_select_form_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='template',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='formsite.teamplates'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='users',
            field=models.ManyToManyField(related_name='forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AuthorizedUser',
        ),
    ]
