# Generated by Django 4.2.4 on 2024-03-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0004_remove_form_stu_list_authorizeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plos',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
