# Generated by Django 4.2.4 on 2024-05-07 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0004_form_template_form_users_delete_authorizeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='year_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1999), django.core.validators.MaxValueValidator(3100)], verbose_name='ปีการศึกษา'),
        ),
    ]
