# Generated by Django 4.2.4 on 2024-02-13 16:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formsite', '0004_answer_userevaluation_plo_clo_answer_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='plo',
            new_name='PLOs',
        ),
    ]
