# Generated by Django 4.2.4 on 2024-02-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0005_rename_plo_plos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
