# Generated by Django 4.2.4 on 2024-04-19 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0005_alter_plos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plos',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='formsite.plos'),
        ),
    ]
