# Generated by Django 4.2.4 on 2024-05-12 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0006_userprofile_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatedata',
            name='type_data',
        ),
        migrations.CreateModel(
            name='CLO',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formsite.teamplates')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='formsite.clo')),
            ],
        ),
    ]
