# Generated by Django 4.2.4 on 2024-05-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0007_remove_templatedata_type_data_clo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clo',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CLO', to='formsite.teamplates'),
        ),
        migrations.AlterField(
            model_name='templatedata',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TemplateData', to='formsite.teamplates'),
        ),
    ]
