# Generated by Django 4.2.4 on 2024-04-22 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0008_plos_active_alter_plos_year_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='formsite.clo'),
        ),
    ]
