# Generated by Django 4.2.4 on 2024-04-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0009_clo_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='plos',
            name='Advtive',
            field=models.BooleanField(default=False),
        ),
    ]
