# Generated by Django 4.2.4 on 2024-04-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0010_plos_advtive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plos',
            name='Advtive',
        ),
    ]
