# Generated by Django 4.2.4 on 2024-05-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0010_remove_course_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='semester',
        ),
    ]
