# Generated by Django 4.2.4 on 2024-05-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0011_remove_form_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='year_number',
        ),
    ]
