# Generated by Django 4.2.4 on 2024-05-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0013_remove_assessmentresponse_response_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentform',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
