# Generated by Django 4.2.4 on 2024-05-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0015_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='section',
            name='start_date',
        ),
    ]
