# Generated by Django 4.2.4 on 2024-05-16 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0016_remove_section_end_date_remove_section_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='formsite.section'),
        ),
    ]
