# Generated by Django 4.2.4 on 2024-05-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0017_alter_form_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='line_token',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
