# Generated by Django 4.2.4 on 2024-05-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0020_teamplates_unique_semester_year'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='form',
            constraint=models.UniqueConstraint(fields=('course', 'class_code', 'section', 'template'), name='unique_course_section_template'),
        ),
    ]
