# Generated by Django 4.2.4 on 2024-05-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0021_form_unique_course_section_template'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='form',
            name='unique_course_section_template',
        ),
    ]
