# Generated by Django 4.2.4 on 2024-05-21 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0022_remove_form_unique_course_section_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='formsite.form'),
        ),
    ]
