# Generated by Django 4.2.4 on 2024-05-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0023_form_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorizeduser',
            old_name='is_teacher',
            new_name='done',
        ),
    ]
