# Generated by Django 4.2.4 on 2024-05-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0024_rename_is_teacher_authorizeduser_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizeduser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
