# Generated by Django 4.2.4 on 2024-05-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0025_authorizeduser_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplates',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamplates',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
