# Generated by Django 4.2.4 on 2024-05-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0026_teamplates_end_date_teamplates_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='form',
            name='start_date',
        ),
    ]
