# Generated by Django 4.2.4 on 2024-01-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Po',
        ),
    ]
